import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

/**
 * `eslint-config-next` is still an eslintrc-style config, so it comes in through
 * FlatCompat rather than being spread directly.
 */
const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // `next-env.d.ts` is generated by Next and uses triple-slash references,
    // which `next/typescript` forbids. It is not ours to fix.
    ignores: [".next/**", "node_modules/**", "out/**", "next-env.d.ts"],
  },
  {
    rules: {
      // Raw archive files are served by the backend with no thumbnail pipeline,
      // so `next/image` has nothing to optimise. Plain <img> is correct here and
      // every use is already annotated at the call site.
      "@next/next/no-img-element": "off",
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
    },
  },
];

export default config;
